# Generated by Django 5.0 on 2026-09-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reports',
            field=models.IntegerField(),
        ),
    ]
